//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace news.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class counter
    {
        public int slid { get; set; }
        public string ipaddress { get; set; }
        public byte[] createddate { get; set; }
    }
}
