//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace news.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Boolean BoolValue
        {
            get; set;
        }
        public string Id { get; set; }
        public string ImageURL { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Author_Id { get; set; }
        public Nullable<int> Catagory_Id { get; set; }
        public string Content { get; set; }
        public Nullable<int> IsBreakingNews { get; set; }
        public Nullable<int> NumOfVisitors { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual User User { get; set; }
    }
}
